language: go

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "tip"

before_install:
  - export GOPATH=$HOME/gopath/src/project-root
  - export PATH=$HOME/gopath/src/project-root/bin:$PATH
  - cd $GOPATH/src/app/webapi
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
    - $HOME/gopath/bin/goveralls